# Generated by Django 2.2.12 on 2022-08-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20220829_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete',
            field=models.NullBooleanField(default=False),
        ),
    ]
