# Generated by Django 2.2.12 on 2022-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20220830_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
